[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = [
  "libnss3-dev",
  "libatk1.0-dev",
  "libatk-bridge2.0-dev", 
  "libcups2-dev",
  "libgbm-dev",
  "libasound2-dev",
  "libpangocairo-1.0-0",
  "libxss1",
  "libgtk-3-dev",
  "libgconf-2-4",
  "xvfb"
]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build:client",
  "npm run build:server"
]

[start]
cmd = "npm start"